In [1]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

pd.set_option('display.max_rows', 300) # specifies number of rows to show
pd.options.display.float_format = '{:40,.4f}'.format # specifies default number format to 4 decimal places
plt.style.use('ggplot') # specifies that graphs should use ggplot styling
%matplotlib inline

In [2]:
raw_data=pd.read_csv('summary_regression_data1.csv')
raw_data.head(5)

,area_name,area_code,total_cases_thousand,cases_density(Number per km2),infectious_rate,small_businesses_density,median_income_2012_thousand,Population_density_thousand,"Proportion_of_population_of_working-age,_2015",Employment_rate_2020,Average_house_price_2020_thousand,population_thousand,small_business_number_2020_thousand
0,Barking and Dagenham,E09000002,26.6530,738.3100,0.1200,0.2200,20.1000,6.0500,63.1000,83.9000,301,218.3700,8.1000
1,Barnet,E09000003,37.7060,434.9000,0.0900,0.3000,29.5000,4.7000,64.9000,90.8000,524,407.1500,25.8000
2,Bexley,E09000004,26.9520,444.7500,0.1100,0.1600,25.5000,4.2100,62.9000,79.5000,341,254.9700,9.8000
3,Brent,E09000005,34.7650,804.7500,0.1000,0.3900,24.3000,7.9600,67.8000,85.6000,477,343.8500,17.0000
4,Bromley,E09000006,30.6630,204.2800,0.0900,0.1100,29.6000,2.2400,62.6000,88.2000,434,336.4000,16.7000

In [3]:
raw_data.columns

Index(['area_name', 'area_code', 'total_cases_thousand',
       'cases_density(Number per km2)', 'infectious_rate',
       'small_businesses_density', 'median_income_2012_thousand',
       'Population_density_thousand',
       'Proportion_of_population_of_working-age,_2015', 'Employment_rate_2020',
       'Average_house_price_2020_thousand', 'population_thousand',
       'small_business_number_2020_thousand'],
      dtype='object')

In [ ]:
# raw_data=raw_data.rename(columns={' total_cases ':'total_cases',' cases_proportion ':'cases_proportion',' small_business_number_2020_thousand ':'small_business_number_2020_thousand'})
# raw_data.columns

In [4]:
raw_data.describe()

,total_cases_thousand,cases_density(Number per km2),infectious_rate,small_businesses_density,median_income_2012_thousand,Population_density_thousand,"Proportion_of_population_of_working-age,_2015",Employment_rate_2020,Average_house_price_2020_thousand,population_thousand,small_business_number_2020_thousand
count,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000,32.0000
mean,28.0272,747.3209,0.0962,0.5863,27.4844,7.8719,68.1188,89.3250,528.9062,287.6034,18.0625
std,7.6992,377.2795,0.0131,0.6280,4.2376,4.0635,3.8925,4.1747,207.6724,63.1906,10.6325
min,12.3290,204.2800,0.0700,0.1000,18.0000,2.2400,62.3000,79.0000,301.0000,160.7900,8.1000
25%,20.5535,444.2175,0.0900,0.2425,24.9500,4.7900,64.8000,87.6500,403.2500,251.9350,12.7000
50%,29.0420,713.7850,0.0950,0.3250,26.8500,6.3500,67.6500,89.5500,465.5000,291.2450,15.5500
75%,33.6362,936.9700,0.1025,0.5950,29.8500,11.4800,71.3250,91.8250,566.5000,333.6475,18.5500
max,41.1710,"1,831.5200",0.1200,2.6600,37.0000,16.5700,75.3000,96.5000,"1,319.0000",407.1500,57.1000

In [ ]:
#raw_data.to_csv('summary_regression_data.csv')

In [ ]:
# #small_businesses_density ~ cases_density_number_per_km2 + population_density_thousand +
#     employment_rate_2020 +
#     average_house_price_2020_thousand

In [ ]:
# df=raw_data.drop(['date','new_cases','area_name','area_code','small_businesses_food_thousand','Square_Kilometres','small_business_number_2020_thousand'],axis=1)
# df.info()

In [ ]:
raw_data.info()

In [ ]:
df=pd.DataFrame(raw_data)

In [ ]:
df['Average_house_price_2020_thousand'] = df['Average_house_price_2020_thousand'].astype(float)
df['total_cases_thousand']=df['total_cases_thousand'].astype(float)

In [ ]:
df.info()

In [ ]:
predictors_df = df.drop(columns=['total_cases_thousand','infectious_rate','Population_density_thousand','small_businesses_density','area_name'], axis=1)
response_df = df[['small_businesses_density']]

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from statsmodels.tools.tools import add_constant

def calculate_vif_(df, thresh=10):
    '''
    Calculates VIF each feature in a pandas dataframe
    A constant must be added to variance_inflation_factor or the results will be incorrect

    :param df: the pandas dataframe containing only the predictor features, not the response variable
    :param thresh: the max VIF value before the feature is removed from the dataframe
    :return: dataframe with features removed
    '''
    const = add_constant(df)
    cols = const.columns
    variables = np.arange(const.shape[1])
    vif_df = pd.Series([variance_inflation_factor(const.values, i) 
               for i in range(const.shape[1])], 
              index=const.columns).to_frame()

    vif_df = vif_df.sort_values(by=0, ascending=False).rename(columns={0: 'VIF'})
    vif_df = vif_df.drop('const')
    vif_df = vif_df[vif_df['VIF'] > thresh]

    print('Features above VIF threshold:\n')
    print(vif_df[vif_df['VIF'] > thresh])

    col_to_drop = list(vif_df.index)

    for i in col_to_drop:
        print('Dropping: {}'.format(i))
        df = df.drop(columns=i)

    return df

In [ ]:
df_predictors_select_VIF = calculate_vif_(predictors_df)
print("The columns remaining after VIF selection are:")
print(df_predictors_select_VIF.columns)

In [ ]:
regressor_OLS = sm.OLS(endog=response_df, exog=sm.add_constant(df_predictors_select_VIF)).fit()
regressor_OLS.summary()